// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXLmNvmuqSeaGpn6ORCTOFKnMXeTrhcM',
    appId: '1:680328691480:web:9ddc734dbcd364fe6be86d',
    messagingSenderId: '680328691480',
    projectId: 'squadhub-efed7',
    authDomain: 'squadhub-efed7.firebaseapp.com',
    storageBucket: 'squadhub-efed7.firebasestorage.app',
    measurementId: 'G-SY777ESHB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzi3aYug3R55GaZ1BNvZ_oAlkEEeYaN4g',
    appId: '1:680328691480:android:6ce6f7122c151f636be86d',
    messagingSenderId: '680328691480',
    projectId: 'squadhub-efed7',
    storageBucket: 'squadhub-efed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIswP-ln3GcTklI1dM2OkH7V7m4gtywoY',
    appId: '1:680328691480:ios:088ad0e2243f1b686be86d',
    messagingSenderId: '680328691480',
    projectId: 'squadhub-efed7',
    storageBucket: 'squadhub-efed7.firebasestorage.app',
    iosBundleId: 'com.example.squadhubPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIswP-ln3GcTklI1dM2OkH7V7m4gtywoY',
    appId: '1:680328691480:ios:088ad0e2243f1b686be86d',
    messagingSenderId: '680328691480',
    projectId: 'squadhub-efed7',
    storageBucket: 'squadhub-efed7.firebasestorage.app',
    iosBundleId: 'com.example.squadhubPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUXLmNvmuqSeaGpn6ORCTOFKnMXeTrhcM',
    appId: '1:680328691480:web:aa64cc5f503a8af06be86d',
    messagingSenderId: '680328691480',
    projectId: 'squadhub-efed7',
    authDomain: 'squadhub-efed7.firebaseapp.com',
    storageBucket: 'squadhub-efed7.firebasestorage.app',
    measurementId: 'G-03XYKMCZF7',
  );
}
